version: "2"

services:
  zk:
    image: bobrik/zookeeper
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
    networks:
      mesos:
        ipv4_address: 10.0.0.10

  master:
    image: mesosphere/mesos-master:1.0.1-2.0.93.ubuntu1404
    environment:
      MESOS_ZK: zk://10.0.0.10:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log
      MESOS_HOSTNAME: 10.0.0.20
      LIBPROCESS_IP: 10.0.0.20
    networks:
      mesos:
        ipv4_address: 10.0.0.20
    depends_on:
      - zk
networks:
  mesos:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          ip_range: 10.0.0.0/24
          gateway: 10.0.0.1