version: "2"

services:
  bootstrap:
    build: ./bootstrap
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mesos:
        ipv4_address: 10.0.0.5

networks:
  mesos:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          ip_range: 10.0.0.0/24
          gateway: 10.0.0.1